# Generated by Django 2.0.7 on 2018-07-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField()),
                ('host_id', models.IntegerField()),
                ('superhost', models.BooleanField()),
                ('response_time', models.CharField(max_length=50, null=True)),
                ('response_rate', models.IntegerField(null=True)),
                ('number_of_reviews', models.IntegerField()),
                ('review_scores_rating', models.IntegerField(null=True)),
                ('host_about', models.TextField(max_length=500, null=True)),
                ('host_verifications', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('visitor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=11)),
                ('english_level', models.CharField(max_length=10)),
                ('visitor_Landlord', models.ManyToManyField(to='fangdong.Landlord')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='landlord',
            unique_together={('listing_id', 'host_id')},
        ),
        migrations.AlterUniqueTogether(
            name='visitors',
            unique_together={('name', 'gender', 'phone')},
        ),
    ]
