# Generated by Django 2.0.7 on 2018-07-14 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fangdong', '0002_auto_20180714_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrecords',
            name='landlord_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_set', to='fangdong.Landlord'),
        ),
        migrations.AlterField(
            model_name='visitrecords',
            name='visitor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors_set', to='fangdong.Visitors'),
        ),
    ]
