# Generated by Django 2.0.7 on 2018-07-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fangdong', '0003_auto_20180714_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrecords',
            name='landlord_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visitrecords',
            name='visitor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='landlord',
            table='landlord',
        ),
        migrations.AlterModelTable(
            name='visitors',
            table='visitors',
        ),
        migrations.AlterModelTable(
            name='visitrecords',
            table='visitor_landlord_relation',
        ),
    ]
