# Generated by Django 2.0.7 on 2018-07-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fangdong', '0006_auto_20180715_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='age',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
