# Generated by Django 2.0.7 on 2018-07-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fangdong', '0008_auto_20180715_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='credulity_question1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='credulity_question2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='credulity_question3',
            field=models.IntegerField(null=True),
        ),
    ]
